/**
 * Lovable Analysis Authority — service module
 *
 * Calls POST {LOVABLE_WM_ANALYZE_URL} with a short-TTL signed S3 URL.
 *
 * Contract rules (non-negotiable):
 * - Strict Zod parse (not safeParse) — fail-fast on schema mismatch.
 * - Preview fields ONLY come from envelope.preview — never from envelope.full.
 * - The entire validated envelope is stored verbatim in analyses.lovable_envelope.
 * - meta.trace_id and meta.analysis_version go into their dedicated DB columns.
 * - On schema mismatch: throw LovableAnalysisError("ANALYSIS_SCHEMA_MISMATCH").
 * - On any failure: throw LovableAnalysisError so the caller sets status='failed'.
 */

import { z } from "zod";
import { ENV } from "../_core/env";
import { storageGet } from "../storage";

// ─── Strict Zod schema (authoritative — from pasted_content_7 spec) ───────────

/**
 * meta block — identifies the analysis run for cross-system debugging.
 */
export const AnalysisMetaSchema = z.object({
  trace_id: z.string().uuid(),
  analysis_version: z.string().min(1),
  model_used: z.string().min(1),
  processing_time_ms: z.number(),
  timestamp: z.string().min(1),
});

/**
 * preview block — safe to show post-email, pre-phone-OTP.
 * Must NOT contain dollar amounts, contractor names, or line items.
 */
export const AnalysisPreviewSchema = z.object({
  score: z.number().int().min(0).max(100),
  grade: z.string().min(1),
  risk_level: z.enum(["critical", "high", "moderate", "acceptable"]),
  headline: z.string().min(1),
  warning_count: z.number().int(),
  missing_item_count: z.number().int(),
});

/**
 * full block — NEVER sent to browser pre-phone-OTP.
 * Stored verbatim; Lovable owns this shape.
 */
export const AnalysisFullSchema = z.object({
  dashboard: z.object({
    overall_score: z.number(),
    final_grade: z.string(),
    safety_score: z.number(),
    scope_score: z.number(),
    price_score: z.number(),
    fine_print_score: z.number(),
    warranty_score: z.number(),
    price_per_opening: z.string(),
    warnings: z.array(z.string()),
    missing_items: z.array(z.string()),
    summary: z.string(),
  }),
  forensic: z.object({
    headline: z.string(),
    risk_level: z.enum(["critical", "high", "moderate", "acceptable"]),
    statute_citations: z.array(z.string()),
    questions_to_ask: z.array(z.string()),
    positive_findings: z.array(z.string()),
    hard_cap_applied: z.boolean(),
    hard_cap_reason: z.string().nullable(),
    hard_cap_statute: z.string().nullable(),
  }),
  extracted_identity: z.object({
    contractor_name: z.string().nullable(),
    license_number: z.string().nullable(),
    noa_numbers: z.array(z.string()),
  }),
});

/**
 * Top-level envelope — the complete response from POST /wm/analyze-quote.
 * Exported so Vitest can import and validate directly.
 */
export const AnalysisEnvelopeSchema = z.object({
  meta: AnalysisMetaSchema,
  preview: AnalysisPreviewSchema,
  full: AnalysisFullSchema,
});

export type AnalysisEnvelope = z.infer<typeof AnalysisEnvelopeSchema>;
export type AnalysisMeta = z.infer<typeof AnalysisMetaSchema>;
export type AnalysisPreview = z.infer<typeof AnalysisPreviewSchema>;
export type AnalysisFull = z.infer<typeof AnalysisFullSchema>;

// ─── Custom error class ───────────────────────────────────────────────────────

export class LovableAnalysisError extends Error {
  constructor(
    message: string,
    public readonly code:
      | "CONFIG_MISSING"
      | "SIGNED_URL_FAILED"
      | "NETWORK_ERROR"
      | "HTTP_ERROR"
      | "INVALID_RESPONSE"
      | "ANALYSIS_SCHEMA_MISMATCH"
      | "TIMEOUT",
    public readonly httpStatus?: number,
    public readonly rawBody?: string
  ) {
    super(message);
    this.name = "LovableAnalysisError";
  }
}

// ─── Request type ─────────────────────────────────────────────────────────────

export interface AnalyzeQuoteRequest {
  /** S3 key of the uploaded file — used to generate a short-TTL signed URL */
  s3Key: string;
  mimeType: string;
  /** Trace ID generated by the caller before the DB record is created */
  trace_id: string;
  /** Optional context fields forwarded to Lovable */
  openingCount?: number;
  areaName?: string;
  notesFromCalculator?: string;
}

// ─── Main service function ────────────────────────────────────────────────────

const TIMEOUT_MS = 60_000; // 60 seconds — analysis can take time

export async function analyzeQuote(
  req: AnalyzeQuoteRequest
): Promise<AnalysisEnvelope> {
  const { lovableAnalysisUrl, lovableAnalysisSharedSecret } = ENV;

  if (!lovableAnalysisUrl || !lovableAnalysisSharedSecret) {
    throw new LovableAnalysisError(
      "LOVABLE_WM_ANALYZE_URL or WM_ANALYZE_QUOTE_SECRET is not configured.",
      "CONFIG_MISSING"
    );
  }

  // Generate a short-TTL signed URL (5 minutes) so Lovable can read the file
  let fileUrl: string;
  try {
    const result = await storageGet(req.s3Key);
    fileUrl = result.url;
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new LovableAnalysisError(
      `Failed to generate signed S3 URL for key "${req.s3Key}": ${msg}`,
      "SIGNED_URL_FAILED"
    );
  }

  // Build request payload per spec
  const payload: Record<string, unknown> = {
    file_url: fileUrl,
    mime_type: req.mimeType,
    trace_id: req.trace_id,
  };
  if (req.openingCount !== undefined) payload.opening_count = req.openingCount;
  if (req.areaName) payload.area_name = req.areaName;
  if (req.notesFromCalculator) payload.notes_from_calculator = req.notesFromCalculator;

  // The URL in ENV is the full endpoint per spec (LOVABLE_WM_ANALYZE_URL)
  const endpoint = lovableAnalysisUrl.replace(/\/+$/, "");

  let rawBody: string;
  let httpStatus: number;

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), TIMEOUT_MS);

    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${lovableAnalysisSharedSecret}`,
        "X-Trace-Id": req.trace_id,
      },
      body: JSON.stringify(payload),
      signal: controller.signal,
    });

    clearTimeout(timeoutId);
    httpStatus = response.status;
    rawBody = await response.text();

    if (!response.ok) {
      throw new LovableAnalysisError(
        `Lovable API returned HTTP ${httpStatus}: ${rawBody.slice(0, 500)}`,
        "HTTP_ERROR",
        httpStatus,
        rawBody
      );
    }
  } catch (err: unknown) {
    if (err instanceof LovableAnalysisError) throw err;
    const msg = err instanceof Error ? err.message : String(err);
    const isTimeout = msg.includes("aborted") || msg.includes("abort");
    throw new LovableAnalysisError(
      isTimeout
        ? `Lovable API timed out after ${TIMEOUT_MS / 1000}s`
        : `Network error calling Lovable API: ${msg}`,
      isTimeout ? "TIMEOUT" : "NETWORK_ERROR"
    );
  }

  // Parse JSON
  let parsed: unknown;
  try {
    parsed = JSON.parse(rawBody);
  } catch {
    throw new LovableAnalysisError(
      `Lovable API returned non-JSON response: ${rawBody.slice(0, 200)}`,
      "INVALID_RESPONSE",
      httpStatus!,
      rawBody
    );
  }

  // Strict parse — fail-fast on schema mismatch (spec: do NOT persist on failure)
  let envelope: AnalysisEnvelope;
  try {
    envelope = AnalysisEnvelopeSchema.parse(parsed);
  } catch (err: unknown) {
    const issues =
      err instanceof z.ZodError
        ? err.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; ")
        : String(err);
    console.error(`[Lovable] Schema mismatch (trace=${req.trace_id}): ${issues}`);
    throw new LovableAnalysisError(
      `Lovable API response failed strict schema validation: ${issues}`,
      "ANALYSIS_SCHEMA_MISMATCH",
      httpStatus!,
      rawBody
    );
  }

  return envelope;
}
